name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is
      placeholder: Brief description of the issue
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      value: |
        1. 
        2. 
        3. 
        ...
      placeholder: Please provide step-by-step instructions
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      value: |
        - Azure Region: 
        - Azure CLI Version: 
        - Bicep CLI Version: 
        - PowerShell/Bash Version: 
        - Operating System: 
      placeholder: Fill in your environment details
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, logs, screenshots, or examples about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to help troubleshoot this issue if needed
          required: false
