name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a question! Please provide as much detail as possible to help us provide the best answer.

        **Note:** For general Azure questions not specific to this project, please consider using [Azure Community Support](https://docs.microsoft.com/answers/topics/azure.html) or [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-bicep).

  - type: input
    id: question-summary
    attributes:
      label: Question Summary
      description: A brief, clear summary of your question
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: question-details
    attributes:
      label: Detailed Question
      description: Provide a detailed explanation of what you're trying to understand or accomplish
      placeholder: Please describe your question in detail
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - General Usage - How to use this project
        - Architecture - Questions about design patterns or structure
        - Configuration - Help with parameters or settings
        - Deployment - Issues with deployment process
        - Best Practices - Seeking recommendations or guidance
        - Integration - How to integrate with other tools/services
        - Troubleshooting - Help diagnosing issues
        - Other - Something else
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your environment, use case, or what you've already tried
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?
        - Any relevant environment details?
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What outcome or answer are you hoping for?
      placeholder: What would a successful resolution look like?

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information, links, or examples that might be helpful
      placeholder: Links to documentation, code examples, error messages, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the project documentation
          required: true
        - label: This question is specifically about this project (not general Azure/Bicep questions)
          required: true
